import type { NextPage } from 'next'
import Head from 'next/head'
import LinkCard from '../components/LinkCard'

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>NextJs template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-16 min-h-screen flex flex-col items-center justify-center flex-grow">
        <h1 className="m-0 leading-[1.15] text-[4rem] text-center">
          Welcome to{' '}
          <a href="https://nextjs.org" className="text-[#0070f3] hover:underline focus:underline active:underline">
            Next.js!
          </a>
        </h1>

        <p className="my-16 leading-[1.5] text-[1.5rem] text-center">
          Get started by editing{' '}
          <code className="font-mono bg-[#fafafa] dark:bg-gray-900 rounded-md p-3 text-[1.1rem]">pages/index.tsx</code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-3xl w-full flex-col sm:w-auto sm:flex-row">
          <LinkCard href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </LinkCard>

          <LinkCard href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </LinkCard>

          <LinkCard href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </LinkCard>

          <LinkCard href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </LinkCard>
        </div>
      </main>
    </div>
  )
}

export default Home
